### ISSUE TITLE
high CPU usage

### ISSUE THREAD

**Issue by Laubeee** [bloomonkey/oai-harvest#24]
Hi, I am currently running this module to crawl 3.67 M articles from doaj.org, which, obviously, takes a while, especially since the the site seems to really limit the bandwidth for performance reasons (it ran over the weekend and is now, after ~65h, only about 40% done)

However I notice there is a constant CPU usage from the crawler-task at about 30%. Any idea why? If anything I'd expect Network and Disk to be affected, but they're not, in fact they do almost nothing..

**Comment by Laubeee** [comment]
Hm, this might be due to the possibility that the harvester never finishes as there are new entries added to the site by the minute. I just saw that doaj.org provides two different metadata formats, and I was just crawling the default one (`oai_dc`), so probably the ~40% progress I made is all there is for `oai_dc`, and the other 60% would be `oai_doaj`.
I will verify if this is true and keep you posted. If it turns out to be the issue, it might be useful to abort harvesting once an entry is harvested that is newer than the date/time when the harvesting was started... Or maybe when there are continuously only very few entries returned per call?

**Comment by Laubeee** [comment]
Okay it seems the issue is Windows having problems with folders containing massive amounts of files. Would be nice to have a mechanism that splits the results into chunks of, lets say, 250'000 or maybe 500'000 files per folder

or, another solution would be to have an option to keep multiple records per file, just the way they come in from the ListRecords call. Right now it is anyway very disk space unfriendly as keeping millions of files of only a few kb needs waay more space (about a third more in my case)
doaj.org returns 600 records per call, so that would mean instead of 3.7M files, the harvester would only write around 6000 files, which is absolutely no problem at all.

**Comment by bloomonkey** [comment]
If the identifiers have any kind of hierarchy, delimited by a particular character, then you can use that character to create sub-directories using the `--subdirs-on` option.  e.g. if identifiers looked like `foo:bar:baz:xyz:123`, you could use `--subdirs-on=':'` to create a directory structure: `foo/bar/baz/xyz/123.oai_dc.xml`

Failing that, it could be an interesting project to integrate something like https://github.com/benosteen/pairtree

**Comment by bloomonkey** [comment]
Parsing XML is CPU bound, so that probably accounts for the high CPU usage.

**Comment by Laubeee** [comment]
nah, CPU usage is definitely windows not being made for folders > 1M files
There was no hierarchy, but what I did was start the harvester several times for different time intervals and saving those to different folders. The first interval was a bit problematic since it seems doaj migrated its database in dec 2017, hence about 1/3 of all documents were in that first interval. But at least it was crawlable at all.

**Comment by bloomonkey** [comment]
Closing as this doesn't seem to be an issue with the harvester
