### ISSUE TITLE
OAI-PMH Dspace

### ISSUE THREAD

**Issue by fbmarques** [bloomonkey/oai-harvest#37]
Hello, with this package can I download files in a DSPACE repository?

**Comment by bloomonkey** [comment]
Hi!

[The DSpace Features page](https://duraspace.org/dspace/about/features/) (expand the section `Completely customizable to fit your need`) suggests that DSpace complies with OAI-PMH for ingest and export. If that's true, then you should be able to use [oai-harvest](https://github.com/bloomonkey/oai-harvest) to download content from the repository 👍
